site_name: requirements
site_url: https://fiware-requirements.readthedocs.org
repo_url: https://github.com/fiware/developmentGuidelines
site_description: requirements Documentation
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_neutral.css"]
google_analytics: ['UA-84866051-2', 'fiware-requirements.readthedocs.io']
nav:
  - Home: index.md
  - 'Membership Levels': GE_Checklist.md
  - Requirement Checklists:
    - 'General Requirements': GE_Requirements.md
    - 'Development Requirements': development.md
    - 'Docker Requirements': docker.md
    - 'Badge & CSS Requirements': project_badges.md
  - Appendices:
    - 'Appendix A: External Contributions': external_contributions.md
    - 'Appendix B: Training Courses': learning_materials.md
    - 'Appendix C: Webhook': repo_webhook.md
    - 'Appendix D: Release Process': release.md
    - 'Appendix E: Development Lifecycle': lifecycle.md
    - 'Appendix F: Templates': GE_roadmap_template.md
    - 'Appendix G: Analytics': analytics_readthedocs.md
    - 'Appendix H: Containerization': docker_templates.md

  
