site_name: requirements
site_url: https://fiware-requirements.readthedocs.org
repo_url: https://github.com/fiware/developmentGuidelines
site_description: requirements Documentation
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_neutral.css"]
google_analytics: ['UA-84866051-2', 'fiware-requirements.readthedocs.io']
pages:
  - Home: index.md
  - 'Requirements Checklist': GE_Checklist.md
  - 'General Requirements': GE_Requirements.md
  - 'Development Requirements': development.md
  - 'Docker': docker.md
  - 'External Contributions': external_contributions.md
  - 'Project Badges': project_badges.md
  - 'Training Courses': learning_materials.md
  - 'Webhook': repo_webhook.md
  - 'Appendix A: Release Process': release.md
  - 'Appendix B: Development Lifecycle': lifecycle.md
  - 'Appendix C: Templates': GE_roadmap_template.md
  - 'Appendix D: Analytics': analytics_readthedocs.md

  
